// Ensure React and h are available
var h = window.h || (window.React && window.React.createElement);
var createClass = window.createClass || (window.React && window.React.createClass);

// Fallback if createClass is not available (PostPreview as functional component)
var PostPreview = createClass ? createClass({
    render: function () {
        var entry = this.props.entry;
        var image = entry.getIn(['data', 'image']);
        var bg = this.props.getAsset(image);
        var date = entry.getIn(['data', 'date']);
        var tags = entry.getIn(['data', 'tags']) || [];

        return h('article', { className: 'post-content' },
            h('header', { className: 'post-header text-center mb-4' },
                h('div', { className: 'post-meta mb-2' },
                    h('span', { className: 'text-white-50' }, date ? date.toString().substring(0, 10) : '')
                ),
                h('h1', { className: 'post-title display-4 fw-bold' }, entry.getIn(['data', 'title'])),
                h('div', { className: 'post-tags mt-3' },
                    // Check if tags is iterable
                    tags && tags.map ? tags.map(function (tag, index) {
                        return h('span', { key: index, className: 'post-tag' }, tag);
                    }) : null
                )
            ),
            h('div', { className: 'post-banner my-5' },
                image ? h('img', { src: bg.toString(), className: 'img-fluid rounded shadow-lg' }) : null
            ),
            h('div', { className: 'post-body' }, this.props.widgetFor('body'))
        );
    }
}) : function (props) {
    var entry = props.entry;
    var image = entry.getIn(['data', 'image']);
    var bg = props.getAsset(image);
    var date = entry.getIn(['data', 'date']);
    var tags = entry.getIn(['data', 'tags']) || [];

    return h('article', { className: 'post-content' },
        h('header', { className: 'post-header text-center mb-4' },
            h('div', { className: 'post-meta mb-2' },
                h('span', { className: 'text-white-50' }, date ? date.toString().substring(0, 10) : '')
            ),
            h('h1', { className: 'post-title display-4 fw-bold' }, entry.getIn(['data', 'title'])),
            h('div', { className: 'post-tags mt-3' },
                tags && tags.map ? tags.map(function (tag, index) {
                    return h('span', { key: index, className: 'post-tag' }, tag);
                }) : null
            )
        ),
        h('div', { className: 'post-banner my-5' },
            image ? h('img', { src: bg.toString(), className: 'img-fluid rounded shadow-lg' }) : null
        ),
        h('div', { className: 'post-body' }, props.widgetFor('body'))
    );
};

CMS.registerPreviewTemplate("posts", PostPreview);

// Register styles
CMS.registerPreviewStyle("/assets/css/style.css");
CMS.registerPreviewStyle("/assets/css/main.css"); // Generated by Jekyll
